server:
  port: 8081
  servlet:
    context-path: /luckymoney

age: 0
name: 邬友
description: 姓名:${name},年龄:${age}岁--------(从yml获取)



limit:
  age: 0
  name: 邬友
  description: 姓名:${limit.name},年龄:${limit.age}岁--------(从配置类获取)